type teacherType = {
  id: Number;
  avatar: string;
  firstName: string;
  lastName: string;
  department?: string;
  subject?: string;
  email: string;
  studentNumber: Number;
};

export const teachers: teacherType[] = [
  {
    id: 1,
    avatar: "JA",
    firstName: "Elnur",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 2,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 3,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 4,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 5,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 6,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 7,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 8,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 9,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 10,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 11,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 12,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 13,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 14,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 15,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 16,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 17,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 18,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 19,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 20,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 21,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 22,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 23,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 24,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 25,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 26,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
  {
    id: 27,
    avatar: "JA",
    firstName: "Cəfər",
    lastName: "Ələsgərov",
    department: "Cəbr və Həndəsə",
    subject: "Xətti cəbr",
    email: "jafaralasgarov@gmail.com",
    studentNumber: 23,
  },
];
